# Generated by Django 3.2.14 on 2022-08-04 14:27

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=200, unique=True, verbose_name='Route Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('duration', models.IntegerField(verbose_name='Duration (days)')),
                ('distance', models.IntegerField(verbose_name='Distance (nautical miles)')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Image')),
            ],
            options={
                'ordering': ['route_name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField(verbose_name='Trip Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('interest', models.ManyToManyField(blank=True, related_name='trip_interest', to=settings.AUTH_USER_MODEL)),
                ('route_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.route')),
            ],
            options={
                'ordering': ['trip_date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_passengers', models.IntegerField(verbose_name='Number of Passengers')),
                ('cabin_type', models.IntegerField(choices=[(0, 'Shared'), (1, 'Private')], default=0, verbose_name='Cabin Type')),
                ('crew_option', models.IntegerField(choices=[(0, 'Passenger Only'), (1, 'Prepared to Crew')], default=0, verbose_name='Option to Crew')),
                ('sailing_exp', models.IntegerField(choices=[(0, 'None'), (1, 'Some'), (2, 'Lots')], default=0, verbose_name='Previous Sailing Experience')),
                ('special_assistance', models.TextField(blank=True, verbose_name='Special Assistance Needs')),
                ('comments', models.TextField(blank=True, verbose_name='Any additional comments')),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('route_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.route')),
                ('trip_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.trip')),
            ],
            options={
                'ordering': ['trip_date'],
            },
        ),
    ]
