# Generated by Django 3.2.14 on 2022-08-03 09:54

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='cabin_type',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='crew_option',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='number_passengers',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='sailing_exp',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_name',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(max_length=80, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(max_length=80, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.IntegerField(verbose_name='Distance (miles)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='duration',
            field=models.IntegerField(verbose_name='Duration (days)'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_passengers', models.IntegerField(verbose_name='Number of Passengers')),
                ('cabin_type', models.IntegerField(choices=[(0, 'Shared'), (1, 'Private')], default=0, verbose_name='Cabin Type')),
                ('crew_option', models.IntegerField(choices=[(0, 'Passenger Only'), (1, 'Prepared to Crew')], default=0, verbose_name='Option to Crew')),
                ('sailing_exp', models.IntegerField(choices=[(0, 'None'), (1, 'Some'), (2, 'Lots')], default=0, verbose_name='Previous Sailing Experience')),
                ('special_assistance', models.CharField(blank=True, max_length=200, verbose_name='Special Assistance Needs')),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Image')),
                ('passenger', models.ManyToManyField(blank=True, related_name='trip_booking', to='bookings.Passenger')),
                ('route_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.route')),
                ('trip_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.trip')),
            ],
            options={
                'ordering': ['trip_date'],
            },
        ),
    ]
